// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusterıBasvuru.DbContext;

#nullable disable

namespace MusterıBasvuru.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    partial class UygulamaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusterıBasvuru.Entity.Log", b =>
                {
                    b.Property<Guid>("logId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Açıklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Basvuru_UID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kayit_Yapan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Kayit_Zaman")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MusteriBasvuru_UID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("logId");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("MusterıBasvuru.Entity.Model.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminUser");
                });

            modelBuilder.Entity("MusterıBasvuru.Entity.Model.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("MusterıBasvuru.Entity.Model.MusteriBasvuru", b =>
                {
                    b.Property<Guid>("Basvuru_UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BasvuruDurum")
                        .HasColumnType("int");

                    b.Property<DateTime>("BasvuruTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Basvurutipi")
                        .HasColumnType("int");

                    b.Property<string>("HataAciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kayit_Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kayit_Yapan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Kayit_Zaman")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MusteriBasvuru_UID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MusteriNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Basvuru_UID");

                    b.ToTable("MusteriBasvuru");
                });

            modelBuilder.Entity("MusterıBasvuru.Entity.Model.Musteriİletisim", b =>
                {
                    b.Property<Guid>("IletısımId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acıklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Basvuru_UID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("GönderilmeSeklı")
                        .HasColumnType("bit");

                    b.Property<Guid>("MusteriBasvuru_UID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IletısımId");

                    b.ToTable("Musteriİletisim");
                });

            modelBuilder.Entity("MusterıBasvuru.Entity.Model.User", b =>
                {
                    b.Property<Guid>("MusteriBasvuru_UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCKimlikNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriBasvuru_UID");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
